name = "CharacterBuffer"
uuid = "aa16fb62-c97c-47f7-aabf-eb19f0484bb3"
authors = ["Siddharth Bhatia <sidb60200@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
